SELECT 
    DQ.*,
    SUM(CASE WHEN DQ.RN_LINEA = 1 THEN DQ.LINETOTAL_PED ELSE 0 END)
    OVER (PARTITION BY DQ.FECHADEF) AS TOTAL_PEDIDOS_FECHA
FROM
(
SELECT 
    FQ.*,
    ROW_NUMBER() OVER (PARTITION BY FQ.DOCENTRY_PED, FQ.LINENUM_PED
                        ORDER BY FQ.DOCENTRY_FACT NULLS LAST) AS RN_LINEA
FROM
(
SELECT 
    V.*,
    --FECHADEF
    (CASE
        --WHEN TO_CHAR(V.FECHAEMISION_FACT, 'DD/MM/YY') IS NOT NULL 
        --THEN TO_CHAR(V.FECHAEMISION_FACT, 'DD/MM/YY')
        WHEN V.DOCENTRY_FACT IS NULL 
        THEN    
            (
                CASE 
                    WHEN V.CLIENT_NAME_CLI LIKE 'LIVERPOOL' and pick.ORDERENTRY IS NULL
                    THEN V.CREATEDATE_PED
                    WHEN V.CLIENT_NAME_CLI LIKE 'LIVERPOOL' and pick.ORDERENTRY IS NOT NULL
                    THEN SYSDATE
                    WHEN V.DOCSTATUS_PED = 'C'
                    THEN V.CREATEDATE_PED
                    WHEN V.DOCSTATUS_PED = 'O'
                    THEN SYSDATE
                    ELSE NULL
                END
            )
        WHEN V.DOCENTRY_FACT IS NOT NULL AND V.FECHAEMISION_FACT IS NULL
        THEN V.CREATEDATE_PED
    END) AS FECHADEF,
    (CASE WHEN V.DOCENTRY_FACT IS NOT NULL THEN 'SI' ELSE 'NO' END) AS TIENE_FACTURA,
    (CASE 
        WHEN V.DOCENTRY_FACT IS NULL AND V.DOCSTATUS_PED = 'O'
        THEN 'Pendiente de facturar'
        WHEN V.DOCSTATUS_PED = 'C'
        THEN 'No facturado'
        WHEN V.DOCENTRY_FACT IS NOT NULL AND V.LINETOTAL_PED > NVL(V.LINETOTAL_FACT,0)
        THEN 'No facturado'
        ELSE 'Facturado'
    END) AS FACTURADO,
    V.LINETOTAL_PED - NVL(V.LINETOTAL_FACT,0) AS IMPORTE_FALTANTE_FACTURA
FROM
(
SELECT
PED.DOCENTRY_PED AS DOCENTRY_PED,
PED.DOCNUM_PED AS DOCNUM_PED,
PED.LINENUM_PED AS LINENUM_PED,
PED.DOCDATE AS DOC_PED,
PED.DOCDUEDATE AS DOCDUE_PED,
PED.TAXDATE AS TAX_PED,
PED.DOCSTATUS AS DOCSTATUS_PED,
PED.CREATEDATE AS CREATEDATE_PED,
PED.CANCELED_PED AS CANCELED_PED,
PED.CARDCODE AS CARDCODE_PED,
PED.CARDNAME AS CARDNAME_PED,
PED.COMMENTS AS COMMENTS_PED,
PED.ITEMCODE AS ITEMCODE_PED,
PED.ITEMNAME AS ITEMNAME_PED,
PED.ITEMCODE_AGROUPED AS ITEMCODE_AGROUPED_PED,
PED.ITEMNAME_AGROUPED AS ITEMNAME_AGROUPED_PED,
PED.ITEMCODE_GROUP AS ITEMCODE_GROUP_PED,
PED.ITEMNAME_GROUP AS ITEMNAME_GROUP_PED,
PED.BRAND AS BRAND_PED,
PED.LINE AS LINE_PED,
PED.RANGE AS RANGE_PED,
PED.REGULATORY_STATUS AS REGULATORY_STATUS_PED,
PED.THERAPEUTIC_AREA AS THERAPEUTIC_AREA_PED,
PED.TYPE AS TYPE_PED,
PED.SUBTYPE AS SUBTYPE_PED,
PED.QUANTITY AS QUANTITY_PED,
PED.OPENQTY AS OPENQTY_PED,
PED.PRICE AS PRICE_PED,
PED.PRICE * PED.QUANTITY AS LINETOTAL_PED,
PED.ACCTCODE AS ACCTCODE_PED,
PED.ACCTNAME AS ACCTNAME_PED,
PED.OCRCODE AS OCRCODE_PED,
PED.OCRNAME AS OCRNAME_PED,
ENTR.DOCENTRY AS DOCENTRY_ENTR,
ENTR.DOCNUM AS DOCNUM_ENTR,
ENTR.BASEENTRY AS BASEENTRY_ENTR,
ENTR.LINENUM AS LINENUM_ENTR,
ENTR.BASELINE AS BASELINE_ENTR,
ENTR.BASETYPE AS BASETYPE_ENTR,
ENTR.FECHAACT AS FECHAACT_ENTR,
ENTR.FECHACRE AS FECHACRE_ENTR,
ENTR.CANCELED AS CANCELED_ENTR,
ENTR.CANTIDADENTREGADA  AS CANTIDADENTREGADA_ENTR,
FACT.DOCENTRY AS DOCENTRY_FACT,
FACT.DOCNUM AS DOCNUM_FACT,
FACT.BASEENTRY AS BASEENTRY_FACT,
FACT.BASELINE AS BASELINE_FACT,
FACT.BASETYPE AS BASETYPE_FACT,
FACT.CANCELED AS CANCELED_FACT,
FACT.FECHAACT AS FECHAACT_FACT,
FACT.FECHACRE AS FECHACRE_FACT,
FACT.PRECIO AS PRECIO_FACT,
FACT.DESCUENTO AS DESCUENTO_FACT,
FACT.PEYMETHOD AS PEYMETHOD_FACT,
FACT.RATE AS RATE_FACT,
FACT.IVAVALUE AS IVAVALUE_FACT,
FACT.IVAGROUP AS IVAGROUP_FACT,
FACT.VATSUM AS VATSUM_FACT,
NVL(FACT.LINETOTAL,0)  AS LINETOTAL_FACT,
FACT.U_FECHAEMISION AS FECHAEMISION_FACT,
PAYS.DOCENTRY_REL AS DOCENTRY_REL_PAG,
PAYS.DOCNUM_PAGOS AS DOCNUM_PAGOS_PAG,
PAYS.CANCELED AS CANCELED_PAG,
PAYS.FECHAACT AS FECHAACT_PAG,
PAYS.FECHACRE AS FECHACRE_PAG,
PAYS.INVTYPE AS INVTYPE_PAG,
PAYS.TRSFRACCT AS TRSFRACCT_PAG,
PAYS.TRSFRSUM AS TRSFRSUM_PAG,
PAYS.TRSFRDATE AS TRSFR_PAG,
PAYS.TRSFRREF AS TRSFRREF_PAG,
PAYS.VATAPPLIED AS VATAPPLIED_PAG,
PAYS.SUMAPPLIED  AS SUMAPPLIED_PAG,
CLI.CLIENT_CODE AS CLIENT_CODE_CLI,
CLI.CLIENT_NAME AS CLIENT_NAME_CLI,
CLI.VAT_TAX_ID AS VAT_TAX_ID_CLI,
CLI.CLIENT_SUBTYPE AS CLIENT_SUBTYPE_CLI,
CLI.CLIENT_SUBTYPE2 AS CLIENT_SUBTYPE2_CLI,
CLI.STATUS AS STATUS_CLI,
CLI.CURRENCY AS CURRENCY_CLI,
CLI.GROUPED_CLIENT_CODE AS GROUPED_CLIENT_CODE_CLI,
CLI.GROUPED_CLIENT_NAME AS GROUPED_CLIENT_NAME_CLI,
CLI.DATE_CLIENT AS DATE_CLIENT_CLI,
CLI.CLIENT_ASSIGNED_SALES_FORCE AS CLIENT_ASSIGNED_SALES_FORCE_CLI,
CLI.NETWORK_TERRITORY AS NETWORK_TERRITORY_CLI,
CLI.FINANCIAL_RISK AS FINANCIAL_RISK_CLI,
CLI.ELECTRONIC_BILLING AS ELECTRONIC_BILLING_CLI,
CLI.PAYMENT_CONDITIONS AS PAYMENT_CONDITIONS_CLI,
CLI.ADDRESS AS ADDRESS_CLI,
CLI.ADDRESS_TYPE AS ADDRESS_TYPE_CLI,
CLI.DATE_ADDRESS AS DATE_ADDRESS_CLI,
CLI.CONTINENT AS CONTINENT_CLI,
CLI.COUNTRY AS COUNTRY_CLI,
CLI.STATE AS STATE_CLI,
CLI.CITY AS CITY_CLI,
CLI.PHONE AS PHONE_CLI,
CLI.EMAIL AS EMAIL_CLI,
CLI.VALIDATE_STATUS AS VALIDATE_STATUS_CLI,
CLI.ACCOUNT_NUM AS ACCOUNT_NUM_CLI,
CLI.ACCOUNT_NAME AS ACCOUNT_NAME_CLI,
CLI.VATGROUP  AS VATGROUP_CLI
FROM
STD_MEX_BI_PEDIDOS ped
LEFT JOIN 
(
SELECT * FROM 
STD_MEX_BI_CLIENTES
WHERE 
UPPER(ADDRESS_TYPE) LIKE '%FISCAL%'
OR CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
OR (CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)>1) 
    AND  
    CLIENT_CODE||'-'||ADDRESS_TYPE IN (
        SELECT CLIENT_CODE||'-'||ADDRESS_TYPE 
        FROM(
        SELECT CLIENT_CODE, MAX(ADDRESS_TYPE) AS ADDRESS_TYPE 
        FROM STD_MEX_BI_CLIENTES 
        WHERE ADDRESS_TYPE<>'Ship To' 
        GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
    )
    )
) 
cli ON ped.CARDCODE = cli.CLIENT_CODE
LEFT JOIN STD_MEX_BI_FACTURAS_CLIENTES fact ON fact.BASETYPE = '15' AND fact.BASEENTRY = entr.DOCENTRY AND fact.BASELINE = entr.LINENUM
LEFT JOIN STD_MEX_BI_PAGOS pays ON pays.INVTYPE = '13' AND pays.DOCENTRY_REL = fact.DOCENTRY
--LEFT JOIN STG_SAP_MX_OPKL 
) V
LEFT JOIN STD_MEX_BI_PICK pick ON pick.ORDERENTRY = V.DOCENTRY_PED
--WHERE V.DOCENTRY_PED = '22565'
) FQ
)DQ
WHERE DQ.GROUPED_CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND EXTRACT(MONTH FROM DQ.FECHADEF) = 8 AND EXTRACT(YEAR FROM DQ.FECHADEF) = 2026 AND DQ.DOCNUM_PED = '21750' AND DQ.RN_LINEA = 1
;
