WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

SET ECHO OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING ON 
SET TERMOUT OFF

SET MARKUP CSV ON DELIMITER ',' QUOTE ON

SPOOL C:\tabcmd\TableauGitHub\lista_workbooks.csv

SELECT WORKBOOK_LUID, WORKBOOK, RUTA_PROYECTO, RUTA_LOCAL_DESTINO, OWNER_EMAIL, ULTIMA_ACTUALIZACION, TIPO_ITEM
FROM DESCARGA_WORKBOOKS;

SPOOL OFF

SET MARKUP CSV OFF

EXIT
