SELECT
    W.*,
    SUM(W.LINETOTAL_PED) OVER (PARTITION BY W.FECHADEF) AS TOTAL_PEDIDOS
FROM
(
SELECT 
    V.*,
    (CASE
        --WHEN V.FECHAEMISION_FACT IS NOT NULL 
        --THEN V.FECHAEMISION_FACT
        WHEN V.DOCENTRY_FACT IS NULL 
        THEN    
            (
                CASE 
                    WHEN V.CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND V.PICKUPDATE_PICK IS NULL
                    THEN V.CREATEDATE_PED
                    WHEN V.CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND V.PICKUPDATE_PICK IS NOT NULL
                    THEN SYSDATE
                    WHEN V.DOCSTATUS_PED = 'C'
                    THEN V.CREATEDATE_PED
                    WHEN V.DOCSTATUS_PED = 'O'
                    THEN SYSDATE
                    ELSE NULL
                END
            )
        WHEN V.DOCENTRY_FACT IS NOT NULL AND V.FECHAEMISION_FACT IS NULL
        THEN V.CREATEDATE_PED
    END) AS FECHADEF,
    (CASE WHEN V.DOCENTRY_FACT IS NOT NULL THEN 'SI' ELSE 'NO' END) AS TIENE_FACTURA,
    (CASE 
        WHEN V.DOCENTRY_FACT IS NULL AND V.DOCSTATUS_PED = 'O'
        THEN 'Pendiente de facturar'
        WHEN V.DOCSTATUS_PED = 'C' AND V.DOCENTRY_FACT IS NULL
        THEN 'No facturado'
        WHEN V.DOCENTRY_FACT IS NOT NULL AND V.LINETOTAL_PED > NVL(V.LINETOTAL_FACT,0)
        THEN 'No facturado'
        ELSE 'Facturado'
    END) AS FACTURADO,
    V.LINETOTAL_PED - NVL(V.LINETOTAL_FACT,0) AS IMPORTE_FALTANTE_FACTURA
FROM
(
SELECT
PED.DOCENTRY_PED AS DOCENTRY_PED,
PED.DOCNUM_PED AS DOCNUM_PED,
PED.LINENUM_PED AS LINENUM_PED,
PED.DOCDATE AS DOC_PED,
PED.DOCDUEDATE AS DOCDUE_PED,
PED.TAXDATE AS TAX_PED,
PED.DOCSTATUS AS DOCSTATUS_PED,
PED.CREATEDATE AS CREATEDATE_PED,
PED.CANCELED_PED AS CANCELED_PED,
PED.CARDCODE AS CARDCODE_PED,
PED.CARDNAME AS CARDNAME_PED,
PED.COMMENTS AS COMMENTS_PED,
PED.ITEMCODE AS ITEMCODE_PED,
PED.ITEMNAME AS ITEMNAME_PED,
PED.ITEMCODE_AGROUPED AS ITEMCODE_AGROUPED_PED,
PED.ITEMNAME_AGROUPED AS ITEMNAME_AGROUPED_PED,
PED.ITEMCODE_GROUP AS ITEMCODE_GROUP_PED,
PED.ITEMNAME_GROUP AS ITEMNAME_GROUP_PED,
PED.BRAND AS BRAND_PED,
PED.LINE AS LINE_PED,
PED.RANGE AS RANGE_PED,
PED.REGULATORY_STATUS AS REGULATORY_STATUS_PED,
PED.THERAPEUTIC_AREA AS THERAPEUTIC_AREA_PED,
PED.TYPE AS TYPE_PED,
PED.SUBTYPE AS SUBTYPE_PED,
PED.QUANTITY AS QUANTITY_PED,
PED.OPENQTY AS OPENQTY_PED,
PED.PRICE AS PRICE_PED,
PED.PRICE * PED.QUANTITY AS LINETOTAL_PED,
PED.ACCTCODE AS ACCTCODE_PED,
PED.ACCTNAME AS ACCTNAME_PED,
PED.OCRCODE AS OCRCODE_PED,
PED.OCRNAME AS OCRNAME_PED,
FACT_AGG.CANTIDAD_FACTURAS AS CANTIDAD_FACTURAS,
FACT_AGG.DOCENTRY_FACT AS DOCENTRY_FACT,
FACT_AGG.DOCNUM_FACT AS DOCNUM_FACT,
FACT_AGG.FECHAEMISION_FACT AS FECHAEMISION_FACT,
FACT_AGG.FACTURAS_ASOCIADAS AS FACTURAS_ASOCIADAS,
NVL(FACT_AGG.TOT_PARTIDA,0) AS LINETOTAL_FACT,
PAGOS_AGG.CANTIDAD_PAGOS AS CANTIDAD_PAGOS,
PAGOS_AGG.TOTAL_PAGADO AS TOTAL_PAGADO,
PAGOS_AGG.TOTAL_TRANSFERIDO AS TOTAL_TRANSFERIDO,
PAGOS_AGG.FECHA_ULTIMO_PAGO AS FECHA_ULTIMO_PAGO,
PAGOS_AGG.PAGOS_ASOCIADOS AS PAGOS_ASOCIADOS,
PICK_AGG.PICKUPDATE_PICK AS PICKUPDATE_PICK,
CLI.CLIENT_CODE AS CLIENT_CODE_CLI,
CLI.CLIENT_NAME AS CLIENT_NAME_CLI,
CLI.VAT_TAX_ID AS VAT_TAX_ID_CLI,
CLI.CLIENT_SUBTYPE AS CLIENT_SUBTYPE_CLI,
CLI.CLIENT_SUBTYPE2 AS CLIENT_SUBTYPE2_CLI,
CLI.STATUS AS STATUS_CLI,
CLI.CURRENCY AS CURRENCY_CLI,
CLI.GROUPED_CLIENT_CODE AS GROUPED_CLIENT_CODE_CLI,
CLI.GROUPED_CLIENT_NAME AS GROUPED_CLIENT_NAME_CLI,
CLI.DATE_CLIENT AS DATE_CLIENT_CLI,
CLI.CLIENT_ASSIGNED_SALES_FORCE AS CLIENT_ASSIGNED_SALES_FORCE_CLI,
CLI.NETWORK_TERRITORY AS NETWORK_TERRITORY_CLI,
CLI.FINANCIAL_RISK AS FINANCIAL_RISK_CLI,
CLI.ELECTRONIC_BILLING AS ELECTRONIC_BILLING_CLI,
CLI.PAYMENT_CONDITIONS AS PAYMENT_CONDITIONS_CLI,
CLI.ADDRESS AS ADDRESS_CLI,
CLI.ADDRESS_TYPE AS ADDRESS_TYPE_CLI,
CLI.DATE_ADDRESS AS DATE_ADDRESS_CLI,
CLI.CONTINENT AS CONTINENT_CLI,
CLI.COUNTRY AS COUNTRY_CLI,
CLI.STATE AS STATE_CLI,
CLI.CITY AS CITY_CLI,
CLI.PHONE AS PHONE_CLI,
CLI.EMAIL AS EMAIL_CLI,
CLI.VALIDATE_STATUS AS VALIDATE_STATUS_CLI,
CLI.ACCOUNT_NUM AS ACCOUNT_NUM_CLI,
CLI.ACCOUNT_NAME AS ACCOUNT_NAME_CLI,
CLI.VATGROUP  AS VATGROUP_CLI
FROM
STD_MEX_BI_PEDIDOS ped
LEFT JOIN 
(
SELECT * FROM 
STD_MEX_BI_CLIENTES
WHERE 
UPPER(ADDRESS_TYPE) LIKE '%FISCAL%'
OR CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
OR (CLIENT_CODE IN (SELECT CLIENT_CODE FROM STD_MEX_BI_CLIENTES GROUP BY CLIENT_CODE HAVING COUNT(1)>1) 
    AND  
    CLIENT_CODE||'-'||ADDRESS_TYPE IN (
        SELECT CLIENT_CODE||'-'||ADDRESS_TYPE 
        FROM(
        SELECT CLIENT_CODE, MAX(ADDRESS_TYPE) AS ADDRESS_TYPE 
        FROM STD_MEX_BI_CLIENTES 
        WHERE ADDRESS_TYPE<>'Ship To' 
        GROUP BY CLIENT_CODE HAVING COUNT(1)=1)
    )
    )
) 
cli ON ped.CARDCODE = cli.CLIENT_CODE
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        COUNT(fact.DOCENTRY) AS CANTIDAD_FACTURAS,
        SUM(fact.LINETOTAL) AS TOT_PARTIDA,
        MAX(fact.DOCENTRY) AS DOCENTRY_FACT,
        MAX(fact.DOCNUM) AS DOCNUM_FACT,
        MAX(fact.U_FECHAEMISION) AS FECHAEMISION_FACT,
        LISTAGG(fact.DOCNUM,', ') WITHIN GROUP (ORDER BY fact.DOCNUM) AS FACTURAS_ASOCIADAS
    FROM 
        STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_ENTREGAS entr ON entr.BASETYPE = '17' AND entr.BASEENTRY = pl.DOCENTRY_PED AND entr.BASELINE = pl.LINENUM_PED
    LEFT JOIN STD_MEX_BI_FACTURAS_CLIENTES fact ON fact.BASETYPE = '15' AND fact.BASEENTRY = entr.DOCENTRY AND fact.BASELINE = entr.LINENUM
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) FACT_AGG ON FACT_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND FACT_AGG.LINENUM_PED = ped.LINENUM_PED
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        COUNT(pays.DOCNUM_PAGOS) AS CANTIDAD_PAGOS,
        SUM(pays.SUMAPPLIED) AS TOTAL_PAGADO,
        SUM(pays.TRSFRSUM) AS TOTAL_TRANSFERIDO,
        MAX(pays.FECHACRE) AS FECHA_ULTIMO_PAGO,
        LISTAGG(pays.DOCNUM_PAGOS,', ') WITHIN GROUP (ORDER BY pays.DOCNUM_PAGOS) AS PAGOS_ASOCIADOS
    FROM
        STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_ENTREGAS entr ON entr.BASETYPE = '17' AND entr.BASEENTRY = pl.DOCENTRY_PED AND entr.BASELINE = pl.LINENUM_PED
    LEFT JOIN STD_MEX_BI_FACTURAS_CLIENTES fact ON fact.BASETYPE = '15' AND fact.BASEENTRY = entr.DOCENTRY AND fact.BASELINE = entr.LINENUM
    LEFT JOIN STD_MEX_BI_PAGOS pays ON pays.INVTYPE = '13' AND pays.DOCENTRY_REL = fact.DOCENTRY
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) PAGOS_AGG ON PAGOS_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND PAGOS_AGG.LINENUM_PED = ped.LINENUM_PED
LEFT JOIN
(
    SELECT
        pl.DOCENTRY_PED,
        pl.LINENUM_PED,
        MAX(pick.UPDATEDATE) AS PICKUPDATE_PICK
    FROM STD_MEX_BI_PEDIDOS pl
    LEFT JOIN STD_MEX_BI_PICK pick ON pick.ORDERENTRY = pl.DOCENTRY_PED
    GROUP BY pl.DOCENTRY_PED, pl.LINENUM_PED
) PICK_AGG ON PICK_AGG.DOCENTRY_PED = ped.DOCENTRY_PED AND PICK_AGG.LINENUM_PED = ped.LINENUM_PED
)V
) W
WHERE W.GROUPED_CLIENT_NAME_CLI LIKE 'LIVERPOOL' AND EXTRACT(MONTH FROM W.FECHADEF) = 8 AND EXTRACT(YEAR FROM W.FECHADEF) = 2026-- AND W.DOCNUM_PED = '21561';

